version: "3.8"

services:
  backend:
    build: ./backend
    container_name: gps-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/gps_data.db:/usr/src/app/gps_data.db
    restart: unless-stopped

